const rotateOptions = (correctAnswer, distractors, seed) => {
  const base = [correctAnswer, ...distractors].slice(0, 4)
  const shift = seed % base.length
  const options = [...base.slice(shift), ...base.slice(0, shift)]
  return { options, correct: options.indexOf(correctAnswer) }
}

const buildQuestion = (base, correctAnswer, distractors, seed) => ({
  ...base,
  ...rotateOptions(correctAnswer, distractors, seed),
  source: 'generated'
})

const scenes = [
  ['A hotel lobby', 'A receptionist is handing a key card to a guest.', ['Several suitcases are being loaded onto a bus.', 'A guest is repairing a lamp.', 'The front doors have been locked.']],
  ['An office meeting room', 'Some employees are reviewing a chart together.', ['The chairs are being stacked outside.', 'A projector is being carried downstairs.', 'The windows have been covered with curtains.']],
  ['A warehouse aisle', 'A worker is scanning labels on some boxes.', ['The shelves are completely empty.', 'A truck is being washed indoors.', 'Some packages are being opened by customers.']],
  ['An outdoor café', 'Customers are seated beneath large umbrellas.', ['The tables are being moved into a kitchen.', 'A waiter is painting a wall.', 'The sidewalk has been closed to traffic.']],
  ['An airport gate', 'Passengers are lining up near a boarding counter.', ['An aircraft is being repaired in a lobby.', 'A clerk is weighing some furniture.', 'The departure screen has been removed.']],
  ['A construction site', 'Two workers are examining a set of plans.', ['A building has been decorated for a party.', 'The workers are planting flowers indoors.', 'Some tools are floating in water.']],
  ['A retail store', 'Clothing has been arranged on display racks.', ['A cashier is sleeping behind the counter.', 'The shelves are being taken to a parking lot.', 'Customers are preparing food.']],
  ['A city park', 'A cyclist is riding along a paved path.', ['A fountain is being installed in an office.', 'Several cars are parked on the grass.', 'The benches have been placed in a river.']],
  ['A restaurant kitchen', 'A chef is stirring ingredients in a large pot.', ['The dishes are being stored under a vehicle.', 'A menu is hanging from the ceiling.', 'Diners are paying at an outdoor kiosk.']],
  ['A train platform', 'A traveler is pulling a suitcase beside a train.', ['The rails are being used as shelves.', 'Passengers are entering a bookstore.', 'A conductor is washing the station windows.']],
  ['A laboratory', 'A researcher is looking through a microscope.', ['Several plants are being sold at a market.', 'The equipment has been packed for a concert.', 'A technician is serving beverages.']],
  ['A conference hall', 'Rows of chairs face a presentation stage.', ['Audience members are swimming near the stage.', 'The lights have been placed on the floor.', 'A speaker is delivering packages outside.']],
  ['A shipping dock', 'Containers are being moved by a large crane.', ['Office supplies are arranged on a desk.', 'A boat is being displayed inside a museum.', 'The dock has been covered with carpet.']],
  ['A reception area', 'A visitor is signing a form at the counter.', ['The receptionist is climbing a ladder.', 'Some documents are being cooked.', 'The waiting area has no furniture.']],
  ['A grocery market', 'Fresh produce is displayed in wooden crates.', ['The customers are wearing construction helmets.', 'A cashier is watering the ceiling.', 'The aisles are blocked by office desks.']],
  ['A maintenance workshop', 'A mechanic is inspecting the engine of a vehicle.', ['The vehicle is being used as a dining table.', 'Some customers are boarding a ferry.', 'The mechanic is arranging flowers.']]
]

const part1 = scenes.map(([scene, answer, distractors], index) => {
  const choiceData = rotateOptions(answer, distractors, index)
  return {
    id: `gen-p1-${String(index + 1).padStart(3, '0')}`,
    part: 'Part 1', category: '照片描述 · 職場場景', difficulty: index % 4 === 0 ? '進階' : '中階',
    scene, prompt: 'Which statement best describes the scene?',
    spoken: choiceData.options.map((line, optionIndex) => `${String.fromCharCode(65 + optionIndex)}. ${line}`).join(' '),
    explanation: `正確敘述抓到圖片中的主要人物、動作與場景：${answer}`,
    tags: ['photograph', 'present continuous', scene.toLowerCase()], source:'generated', ...choiceData
  }
})

const contexts = [
  {document:'signed contract',location:'reception desk',event:'vendor briefing',time:'two thirty',person:'Ms. Rivera',department:'purchasing',reason:'the presenter is ill',task:'review the supplier bids',duration:'three days',frequency:'twice a month'},
  {document:'expense report',location:'finance office',event:'budget meeting',time:'nine fifteen',person:'Mr. Wallace',department:'accounting',reason:'the quarterly figures are incomplete',task:'approve the travel budget',duration:'about an hour',frequency:'every Friday'},
  {document:'delivery receipt',location:'loading dock',event:'safety inspection',time:'eleven o’clock',person:'Ms. Okafor',department:'operations',reason:'the inspector’s flight was delayed',task:'check the warehouse equipment',duration:'two weeks',frequency:'once a quarter'},
  {document:'training certificate',location:'human resources office',event:'orientation session',time:'ten thirty',person:'Mr. Lin',department:'human resources',reason:'the training room is unavailable',task:'welcome the new employees',duration:'ninety minutes',frequency:'every other Monday'},
  {document:'maintenance request',location:'security desk',event:'equipment demonstration',time:'one forty-five',person:'Ms. Bennett',department:'facilities',reason:'a replacement part has not arrived',task:'inspect the ventilation system',duration:'four hours',frequency:'once a year'},
  {document:'catering invoice',location:'event office',event:'awards luncheon',time:'twelve noon',person:'Mr. Dubois',department:'events',reason:'the main dining room is being renovated',task:'confirm the guest list',duration:'two hours',frequency:'every spring'},
  {document:'shipping manifest',location:'customs counter',event:'export workshop',time:'three twenty',person:'Ms. Garcia',department:'logistics',reason:'the shipment is still at the port',task:'verify the customs forms',duration:'five business days',frequency:'three times a week'},
  {document:'design proposal',location:'project office',event:'client presentation',time:'four o’clock',person:'Mr. Ahmed',department:'design',reason:'the client requested additional samples',task:'update the product drawings',duration:'one month',frequency:'every Wednesday'},
  {document:'room reservation',location:'hotel front desk',event:'tour group arrival',time:'six fifteen',person:'Ms. Rossi',department:'guest services',reason:'the bus is caught in traffic',task:'prepare the welcome packets',duration:'four nights',frequency:'every summer'},
  {document:'software license',location:'IT help desk',event:'system upgrade',time:'seven thirty',person:'Mr. Park',department:'information technology',reason:'the server test is not complete',task:'install the security update',duration:'forty minutes',frequency:'once a month'}
]

const responseTemplates = [
  context => ({spoken:`Where should I leave the ${context.document}?`,answer:`At the ${context.location}.`,wrong:[`It was signed yesterday.`,`Only one copy, please.`],explanation:'Where 詢問地點，答案直接提供文件放置處。',tags:['where question','location']}),
  context => ({spoken:`When will the ${context.event} begin?`,answer:`At ${context.time}.`,wrong:[`In the larger room.`,`It lasted ${context.duration}.`],explanation:'When 詢問開始時間。',tags:['when question','schedule']}),
  context => ({spoken:`Who is going to ${context.task}?`,answer:`${context.person} from ${context.department}.`,wrong:[`It should take ${context.duration}.`,`In the conference room.`],explanation:'Who 詢問負責的人。',tags:['who question','responsibility']}),
  context => ({spoken:`Why was the ${context.event} postponed?`,answer:`Because ${context.reason}.`,wrong:[`For ${context.duration}.`,`At ${context.time}.`],explanation:'Why 詢問原因，because 引出合理理由。',tags:['why question','reason']}),
  context => ({spoken:`How long will it take to ${context.task}?`,answer:`About ${context.duration}.`,wrong:[`At the ${context.location}.`,`${context.person} will.`],explanation:'How long 詢問所需時間。',tags:['how long','duration']}),
  context => ({spoken:`How often is the ${context.event} held?`,answer:`${context.frequency}.`,wrong:[`For ${context.duration}.`,`At ${context.time}.`],explanation:'How often 詢問頻率。',tags:['how often','frequency']}),
  context => ({spoken:`Could you take this ${context.document} to the ${context.location}?`,answer:`Sure, I’m heading there now.`,wrong:[`It was a long document.`,`The event begins at ${context.time}.`],explanation:'Could you… 是請求，答應並表示會執行最自然。',tags:['request','indirect response']}),
  context => ({spoken:`Haven’t you finished the ${context.document} yet?`,answer:`Not yet—I’m checking one final detail.`,wrong:[`Yes, the desk is near the entrance.`,`For about ${context.duration}.`],explanation:'否定疑問句詢問完成狀態，Not yet 為適當回應。',tags:['negative question','status']}),
  context => ({spoken:`Did ${context.person} approve the ${context.document}?`,answer:`No, it’s still being reviewed.`,wrong:[`At the ${context.location}.`,`She arrives at ${context.time}.`],explanation:'Did 開頭的一般問句需要肯定或否定狀態回應。',tags:['yes-no question','approval']}),
  context => ({spoken:`Which room is being used for the ${context.event}?`,answer:`The one beside the ${context.location}.`,wrong:[`${context.frequency}.`,`${context.person} organized it.`],explanation:'Which 詢問選擇，答案指出特定房間。',tags:['which question','meeting room']}),
  context => ({spoken:`The ${context.event} starts at ${context.time}, doesn’t it?`,answer:`Actually, it was moved to a later time.`,wrong:[`The entrance is on the left.`,`I attended for ${context.duration}.`],explanation:'附加問句可用更正資訊間接回應。',tags:['tag question','schedule change']}),
  context => ({spoken:`Would you rather ${context.task} today or tomorrow?`,answer:`Tomorrow would be better for me.`,wrong:[`It belongs to ${context.department}.`,`At the ${context.location}.`],explanation:'Would you rather 提供選項，回答偏好的時間最適當。',tags:['choice question','preference']})
]

const part2 = responseTemplates.flatMap((template, templateIndex) => contexts.map((context, contextIndex) => {
  const item = template(context)
  return buildQuestion({
    id:`gen-p2-${String(templateIndex * contexts.length + contextIndex + 1).padStart(3,'0')}`,
    part:'Part 2', category:'應答問題 · 商務溝通', difficulty:templateIndex > 7 ? '進階' : '中階',
    spoken:item.spoken, prompt:'選出最適當的回應。', explanation:item.explanation, tags:item.tags
  }, item.answer, item.wrong, templateIndex + contextIndex)
}))

const conversations = [
  {category:'物流 · 延遲交貨',script:[['W','The display stands for tomorrow’s trade show still have not arrived.'],['M','I called the carrier. The truck had a mechanical problem, but a replacement vehicle will deliver them by six.'],['W','Good. I’ll ask the convention center to keep the loading entrance open.']],questions:[['Why is the woman concerned?','Some display equipment is late.',['A trade show was canceled.','A truck entrance is too small.','The convention center is closed.']],['What did the man do?','He contacted the carrier.',['He repaired a vehicle.','He ordered new stands.','He visited the convention center.']],['What will the woman most likely do next?','Call the convention center.',['Drive a replacement truck.','Cancel the exhibition.','Prepare a sales invoice.']]]},
  {category:'軟體 · 登入問題',script:[['M','Several new employees cannot sign in to the scheduling platform.'],['W','Their temporary passwords expired last night. I can issue new ones this afternoon.'],['M','Please send the login instructions to their supervisors as well.']],questions:[['What problem is mentioned?','Some employees cannot access a system.',['A schedule has incorrect dates.','A training room is unavailable.','Some supervisors are absent.']],['What does the woman offer to do?','Create new passwords.',['Schedule an afternoon meeting.','Hire additional employees.','Repair a computer screen.']],['Who should also receive the instructions?','The employees’ supervisors.',['The software vendor.','The building manager.','The accounting staff.']]]},
  {category:'飯店 · 團體入住',script:[['W','The conference group will arrive two hours earlier than expected.'],['M','Most rooms are ready, but housekeeping is still working on the sixth floor.'],['W','I’ll prepare refreshments in the lounge while the guests wait.']],questions:[['What has changed?','A group will arrive early.',['A conference moved upstairs.','A hotel reduced its rates.','A lounge will close.']],['What does the man say about the rooms?','Some are still being prepared.',['All of them are occupied.','They have new furniture.','They are on the first floor.']],['What will the woman do?','Arrange refreshments.',['Clean the sixth floor.','Change the room rates.','Contact a travel agency.']]]},
  {category:'採購 · 樣品確認',script:[['M','The supplier sent three fabric samples, but none matches the color in our design.'],['W','I’ll photograph them and ask whether a darker shade is available.'],['M','Thanks. We need to choose the material before Friday’s production meeting.']],questions:[['What problem do the speakers discuss?','The samples are the wrong color.',['A design file is missing.','A supplier charged too much.','A meeting room is unavailable.']],['What will the woman do?','Ask about another shade.',['Return a camera.','Cancel a production meeting.','Order office furniture.']],['Why must a decision be made soon?','A meeting will take place on Friday.',['A discount expires tomorrow.','A shipment leaves tonight.','A designer is going on vacation.']]]},
  {category:'餐廳 · 活動訂位',script:[['W','I’d like to reserve the private dining room for our retirement dinner next Thursday.'],['M','It is available after seven, and it seats up to thirty people.'],['W','That works. I’ll confirm the final guest count on Monday.']],questions:[['Why is the woman speaking with the man?','To reserve a room.',['To apply for a job.','To change a menu price.','To report damaged furniture.']],['What does the man say about the room?','It can hold thirty people.',['It has been renovated.','It closes before seven.','It is near the kitchen.']],['What will the woman provide later?','The number of guests.',['A payment receipt.','A retirement gift.','A list of menu prices.']]]},
  {category:'設施 · 維修安排',script:[['M','The air conditioner in the east conference room is making a loud noise.'],['W','A technician can inspect it after the morning seminar ends.'],['M','I’ll move the client meeting to Room 204 just in case.']],questions:[['What problem is mentioned?','An air conditioner is noisy.',['A seminar is too crowded.','A room number is incorrect.','A client missed a meeting.']],['When can a technician inspect the equipment?','After a seminar.',['Before the building opens.','During the client meeting.','Next month.']],['What will the man do?','Use a different room.',['Cancel a seminar.','Order new equipment.','Contact the client’s technician.']]]},
  {category:'行銷 · 廣告校稿',script:[['W','The online advertisement looks good, but the store address is missing the suite number.'],['M','I’ll correct it before the campaign goes live at noon.'],['W','Please check the mobile version too. The text looked crowded on my phone.']],questions:[['What error did the woman find?','Part of an address is missing.',['A product price is wrong.','A photograph is outdated.','A campaign date has changed.']],['What will the man do before noon?','Correct the advertisement.',['Visit a retail store.','Buy a new phone.','Print a campaign report.']],['What else does the woman ask the man to check?','The mobile version.',['The advertising budget.','The store entrance.','The product inventory.']]]},
  {category:'旅遊 · 航班調整',script:[['M','My afternoon flight was canceled, and the next direct flight is not until tomorrow.'],['W','There is an evening flight with one connection through Denver.'],['M','Please book that one. I need to reach the sales meeting by eight tomorrow morning.']],questions:[['What problem does the man have?','His flight was canceled.',['He lost his passport.','He missed a sales meeting.','His hotel reservation expired.']],['What option does the woman suggest?','A connecting flight.',['A train through Denver.','A morning bus.','A direct evening flight.']],['Why does the man accept the option?','He has an early meeting.',['He wants to visit Denver.','He needs to reduce travel costs.','He plans to stay another night.']]]}
]

const part3 = conversations.flatMap((conversation, conversationIndex) => conversation.questions.map((question, questionIndex) => buildQuestion({
  id:`gen-p3-${String(conversationIndex * 3 + questionIndex + 1).padStart(3,'0')}`,
  part:'Part 3', category:conversation.category, difficulty:questionIndex === 2 ? '進階' : '中階', group:`Conversation ${conversationIndex + 1}`,
  script:conversation.script.map(([speaker,text]) => ({speaker,text})), prompt:question[0],
  explanation:`對話中的關鍵資訊可改寫為：${question[1]}`, tags:['conversation', questionIndex === 2 ? 'inference / next action' : 'detail']
}, question[1], question[2], conversationIndex + questionIndex)))

const talks = [
  {category:'公告 · 停車場',text:'Attention employees. The west parking lot will be closed on Tuesday while new lighting is installed. Please use the visitor lot across from the main entrance. A shuttle will run every fifteen minutes from seven to ten in the morning.',questions:[['What is the purpose of the announcement?','To explain a temporary parking change.',['To advertise a new office location.','To recruit shuttle drivers.','To announce a company holiday.']],['Why will the west lot be closed?','Lighting will be installed.',['The pavement will be cleaned.','A visitor event will be held.','The entrance will be widened.']],['What service will be available?','A morning shuttle.',['Free vehicle repairs.','Reserved visitor spaces.','A bicycle rental.']]]},
  {category:'電話留言 · 訂單',text:'Hello, Ms. Cole. This is Adrian from Mason Office Supply. The ergonomic chairs you ordered are ready, but the blue model is temporarily out of stock. We can deliver the gray model this Friday or the blue one next Wednesday. Please call me before four today with your preference.',questions:[['Why is the speaker calling?','To discuss a product choice.',['To confirm a job interview.','To collect an overdue payment.','To cancel a store opening.']],['What is unavailable?','A blue chair model.',['A delivery truck.','A payment method.','An office desk.']],['What is the listener asked to do?','Call before four.',['Visit the store on Friday.','Send a color sample.','Pay for express delivery.']]]},
  {category:'廣播 · 火車服務',text:'Passengers traveling to Brighton should note that the 9:20 train will depart from Platform 6 instead of Platform 4. The change is due to maintenance work. Please allow extra time to reach the platform, and keep your ticket available for inspection.',questions:[['Who is the announcement for?','Passengers going to Brighton.',['Station maintenance workers.','Travel agency employees.','Passengers arriving from Platform 6.']],['What has changed?','The departure platform.',['The ticket price.','The destination.','The departure time.']],['What are passengers advised to do?','Allow additional time.',['Purchase a new ticket.','Leave their luggage at the desk.','Wait near Platform 4.']]]},
  {category:'介紹 · 新進員工',text:'I am pleased to introduce Dr. Elena Silva, our new research director. She previously led a renewable-energy team in Madrid and has published more than twenty articles. After today’s staff meeting, she will host an informal question-and-answer session in the cafeteria.',questions:[['What is the speaker doing?','Introducing a new director.',['Presenting a research award.','Announcing a retirement.','Reviewing a journal article.']],['What is mentioned about Dr. Silva?','She led a team in Madrid.',['She designed the cafeteria.','She joined the company twenty years ago.','She will publish an article today.']],['What will happen after the meeting?','A question-and-answer session.',['A laboratory inspection.','A formal dinner.','A trip to Madrid.']]]},
  {category:'商店 · 促銷',text:'This weekend only, Harbor Home customers can save twenty percent on all kitchen appliances. Free delivery is included for purchases over five hundred dollars. Members of our rewards program will also receive double points. Visit the service desk if you would like to enroll.',questions:[['What is being advertised?','A weekend sale.',['A cooking class.','A home repair service.','A new restaurant.']],['When is free delivery offered?','For purchases over five hundred dollars.',['For rewards members only.','On small appliances.','After the weekend.']],['Where can customers join the rewards program?','At the service desk.',['On the delivery truck.','In the kitchen department.','At a restaurant.']]]},
  {category:'語音導覽 · 博物館',text:'Welcome to the City Design Museum. Your admission includes the architecture exhibit on the second floor and a guided tour at two o’clock. The sculpture gallery is closed today for a private event. Lockers are available beside the ticket counter.',questions:[['What is included with admission?','A guided tour.',['A private sculpture event.','A meal at the museum café.','A design workshop.']],['What is unavailable today?','The sculpture gallery.',['The second floor.','The ticket counter.','The lockers.']],['Where are the lockers?','Beside the ticket counter.',['Inside the architecture exhibit.','Near the museum café.','On the guided tour route.']]]},
  {category:'公司訊息 · 福利',text:'Beginning next month, employees may use the fitness center in the Lakeside Building at no charge. To receive an access card, complete the wellness form on the company portal. Cards will be distributed by Human Resources every Wednesday afternoon.',questions:[['What new benefit is announced?','Free access to a fitness center.',['Discounted medical insurance.','A monthly transportation pass.','Free meals on Wednesdays.']],['What must employees do first?','Complete an online form.',['Visit the Lakeside Building.','Attend a Wednesday meeting.','Pay a card deposit.']],['Who will distribute access cards?','Human Resources.',['Fitness instructors.','Building security.','Portal administrators.']]]},
  {category:'活動 · 天候變更',text:'Due to the forecast for heavy rain, tomorrow’s outdoor product demonstration will be moved to the Grand Ballroom. The starting time remains ten o’clock. Exhibitors should bring their equipment through the hotel’s north entrance between eight and nine thirty.',questions:[['Why has the event location changed?','Heavy rain is expected.',['More exhibitors registered.','The ballroom equipment failed.','The hotel entrance is closed.']],['What remains the same?','The starting time.',['The outdoor location.','The delivery entrance.','The equipment schedule.']],['When should exhibitors bring in equipment?','Before nine thirty.',['At ten o’clock.','This afternoon.','After the demonstration.']]]}
]

const part4 = talks.flatMap((talk, talkIndex) => talk.questions.map((question, questionIndex) => buildQuestion({
  id:`gen-p4-${String(talkIndex * 3 + questionIndex + 1).padStart(3,'0')}`,
  part:'Part 4', category:talk.category, difficulty:questionIndex === 0 ? '中階' : '進階', group:`Talk ${talkIndex + 1}`,
  spoken:talk.text, prompt:question[0], explanation:`獨白中的關鍵訊息是：${question[1]}`, tags:['short talk', questionIndex === 0 ? 'purpose' : 'detail']
}, question[1], question[2], talkIndex + questionIndex)))

const grammarTemplates = [
  context => [`The ${context.document} must be submitted _____ Friday.`, 'by', ['from','among','during'], 'by + 時間點表示截止期限。', ['preposition','deadline']],
  context => [`Employees are encouraged to _____ feedback after the ${context.event}.`, 'provide', ['provider','provided','provision'], 'to 後面使用原形動詞 provide。', ['verb form','collocation']],
  context => [`${context.person} was selected because of _____ experience in ${context.department}.`, 'extensive', ['extend','extensively','extension'], '名詞 experience 前需要形容詞 extensive。', ['word form','adjective']],
  context => [`The ${context.event} was postponed _____ ${context.reason}.`, 'because of', ['because','although','despite of'], '後面是名詞片語時使用 because of。', ['conjunction','reason']],
  context => [`Neither the manager nor the assistants _____ available at ${context.time}.`, 'were', ['was','be','has been'], '動詞與較近的複數主詞 assistants 一致。', ['subject-verb agreement']],
  context => [`The new process for the ${context.document} is more efficient _____ the previous one.`, 'than', ['as','then','of'], '比較級 more efficient 後接 than。', ['comparative']],
  context => [`Please verify the address before _____ the ${context.document}.`, 'sending', ['send','sent','to send'], '介系詞 before 後可接動名詞 sending。', ['gerund','preposition']],
  context => [`The ${context.event} has become increasingly _____ with local businesses.`, 'popular', ['popularity','popularly','popularize'], 'become 後需要形容詞作主詞補語。', ['word form','linking verb']],
  context => [`The workshop will begin as soon as ${context.person} _____.`, 'arrives', ['arrive','arrived','will arrive'], '時間子句談未來仍使用現在式。', ['time clause','present tense']],
  context => [`Due to _____ demand for the ${context.event}, an additional session has been scheduled.`, 'increased', ['increase','increasingly','increases'], '名詞 demand 前需要形容詞 increased。', ['participle adjective','demand']]
]

const part5 = grammarTemplates.flatMap((template, templateIndex) => contexts.map((context, contextIndex) => {
  const [prompt, answer, distractors, explanation, tags] = template(context)
  return buildQuestion({
    id:`gen-p5-${String(templateIndex * contexts.length + contextIndex + 1).padStart(3,'0')}`,
    part:'Part 5', category:tags.includes('word form') ? '字彙 · 詞性' : '文法 · 句子填空', difficulty:templateIndex > 6 ? '進階' : '中階',
    prompt, explanation, tags
  }, answer, distractors, templateIndex + contextIndex)
}))

const completionPassages = [
  {category:'電子郵件 · 課程通知',passage:'To: All Sales Staff\nSubject: Presentation Workshop\nThe communication workshop has been [1] for June 12. It will focus on explaining complex information [2] and responding to client questions. Please register by Friday [3] space is limited. [4]',blanks:[['scheduled',['scheduling','schedule','schedules'],'現在完成式被動需要過去分詞 scheduled。'],['clearly',['clear','cleared','clearness'],'副詞 clearly 修飾 explaining。'],['because',['although','unless','during'],'because 引出需要提前報名的原因。'],['A confirmation will be sent to registered participants.',['The parking lot was painted last year.','Our products are available in three colors.','The cafeteria closes at noon.'],'確認信與前文報名流程銜接。']]},
  {category:'公告 · 辦公室搬遷',passage:'Our customer service team will move to the third floor next Monday. The new area is [1] than our current space and includes two private meeting rooms. Employees should label all boxes [2] the move. Facilities staff will transport computer equipment. [3], personal items must be packed by each employee. [4]',blanks:[['larger',['largest','largely','large'],'比較結構 than 前使用 larger。'],['before',['while','until','despite'],'before the move 表示搬遷前。'],['However',['For example','Similarly','Therefore of'],'前後為轉折關係。'],['Contact Facilities if you need additional packing materials.',['Customers may order products online.','The annual picnic was successful.','Sales increased last quarter.'],'補充搬遷所需協助最合理。']]},
  {category:'信件 · 訂單更新',passage:'Thank you for your recent order from Bellwood Furnishings. Two of the items are ready for immediate [1]. The remaining desk will arrive at our warehouse on Thursday. We can send everything together, [2] we can make two separate deliveries. Please let us know which option you [3]. [4]',blanks:[['delivery',['deliver','delivered','delivering'],'形容詞 immediate 後需要名詞 delivery。'],['or',['but','so that','despite'],'or 連接兩個可選方案。'],['prefer',['preference','preferable','preferring'],'主詞 you 後需要動詞 prefer。'],['There is no additional charge for separate delivery.',['The showroom was closed last winter.','Wooden desks are difficult to assemble.','Our accountant is on vacation.'],'說明分開配送的費用，承接選項。']]},
  {category:'新聞稿 · 新據點',passage:'Norton Analytics announced yesterday that it will open a regional office in Brisbane. The location was chosen [1] its access to skilled technology workers. Renovation of the building is currently [2] and should finish in August. The company expects to hire sixty employees [3] the end of the year. [4]',blanks:[['because of',['because','although','instead'],'後接名詞片語時用 because of。'],['underway',['under','undergo','underneath'],'underway 表示正在進行。'],['by',['until of','among','since'],'by the end of the year 表截止時間。'],['Recruitment will begin next month.',['The office furniture was inexpensive.','Brisbane has several public parks.','Yesterday was a national holiday.'],'徵才與開設新據點、雇用員工直接相關。']]},
  {category:'備忘錄 · 安全規範',passage:'All laboratory personnel must complete the updated safety course. The online modules can be accessed [1] the employee portal. After viewing each module, participants must answer a short quiz. A score of eighty percent is [2] to continue. Employees who have already completed similar training are not [3] from this requirement. [4]',blanks:[['through',['between','beside','toward'],'through the portal 表示透過系統。'],['required',['require','requiring','requirement'],'被動語態需要過去分詞 required。'],['exempt',['empty','equal','exact'],'be exempt from 是固定搭配。'],['The course must be finished by September 30.',['The cafeteria offers vegetarian meals.','The company picnic is outdoors.','Several microscopes were purchased.'],'補充課程期限最符合段落主題。']]},
  {category:'廣告 · 會員方案',passage:'Join the Metro Arts membership program and enjoy unlimited admission for one year. Members also receive [1] invitations to exhibition previews and a ten-percent discount at the museum shop. Family plans are [2] for households of up to five people. Applications may be completed online or [3] at the ticket desk. [4]',blanks:[['exclusive',['exclude','exclusively','exclusion'],'名詞 invitations 前需要形容詞 exclusive。'],['available',['availability','avail','availably'],'be available 是「可供使用」。'],['in person',['personally of','on person','by a person'],'in person 表示親自辦理。'],['Membership fees support educational programs.',['The train station has two platforms.','The shop sells office chairs.','Preview invitations are printed in blue.'],'說明會員費用途，適合作結尾。']]},
  {category:'通知 · 系統維護',passage:'The online reservation system will be unavailable from 11 p.m. Saturday until 3 a.m. Sunday while technicians install an update. Reservations saved before the maintenance period will not be [1]. Users are advised to complete urgent bookings [2] Saturday evening. The update is expected to improve page-loading speed [3] twenty percent. [4]',blanks:[['affected',['effected','affecting','affection'],'被動語態且語意為受到影響，使用 affected。'],['before',['between','throughout','unless'],'維護開始前完成預訂。'],['by',['at','from','between'],'improve by twenty percent 表示提升幅度。'],['We apologize for any inconvenience.',['Technicians wear identification badges.','Sunday is the first day of the week.','Reservations can include two names.'],'維護通知常以致歉結尾。']]}
]

const part6 = completionPassages.flatMap((item, passageIndex) => item.blanks.map((blank, blankIndex) => buildQuestion({
  id:`gen-p6-${String(passageIndex * 4 + blankIndex + 1).padStart(3,'0')}`,
  part:'Part 6', category:item.category, difficulty:blankIndex === 3 ? '進階' : '中階', group:`Text ${passageIndex + 1}`,
  passage:item.passage, prompt:`Choose the best answer for blank [${blankIndex + 1}].`, explanation:blank[2], tags:['text completion', blankIndex === 3 ? 'sentence insertion' : 'context grammar']
}, blank[0], blank[1], passageIndex + blankIndex)))

const readingPassages = [
  {category:'電子郵件 · 客戶服務',passage:'From: service@novaprint.example\nTo: Lena Ortiz\nSubject: Replacement order\nDear Ms. Ortiz, We inspected the photographs you sent and confirmed that ten brochures in order NP-481 were cut incorrectly. A replacement batch is being printed today and will be shipped by express service tomorrow morning. You do not need to return the damaged brochures. We have also added a credit of $25 to your account for a future purchase. —Devon Hale, Customer Service',questions:[['Why was the e-mail sent?','To explain how a problem will be resolved.',['To request payment for an order.','To advertise a printing service.','To change a delivery address.']],['What was wrong with the brochures?','They were cut incorrectly.',['They had the wrong photographs.','They arrived too late.','They were printed in the wrong language.']],['What will happen tomorrow?','Replacement brochures will be shipped.',['A customer will visit the printer.','A refund check will be mailed.','The damaged items will be collected.']],['What was added to the customer’s account?','A purchase credit.',['An express fee.','A new address.','A photograph file.']]]},
  {category:'廣告 · 專業服務',passage:'RIVER CITY LANGUAGE SERVICES\nClear communication for global business\n• Translation in 18 languages\n• Same-day review for documents under 1,000 words\n• On-site interpretation for conferences and factory tours\nNew corporate clients: Request a free sample translation before September 15 and receive 15% off your first project. Call 555-0184 or visit rivercitylanguages.example.',questions:[['What service is advertised?','Business language support.',['International shipping.','Conference room rental.','Factory equipment repair.']],['What can be reviewed on the same day?','Short documents.',['All conference recordings.','Factory safety plans only.','Projects requested after September 15.']],['Who can receive a discount?','New corporate clients.',['Former employees.','Tour guides.','Language teachers.']],['What is offered at no cost?','A sample translation.',['On-site interpretation.','A factory tour.','A full first project.']]]},
  {category:'即時訊息 · 專案協作',passage:'10:12 Mina: Has the photographer uploaded the lobby pictures?\n10:14 Joel: Yes, but the evening shots are too dark for the website.\n10:15 Mina: Can he return tomorrow morning? The lobby gets better natural light then.\n10:18 Joel: He is at another property tomorrow. I can brighten the best image and send you a preview by 2:00.\n10:19 Mina: Great. If it looks natural, we’ll use it in Friday’s update.',questions:[['What are the speakers discussing?','A photograph for a website.',['A hotel room reservation.','A property sales contract.','An evening event.']],['What problem does Joel mention?','Some images are too dark.',['The website is unavailable.','The photographer is late.','The lobby is being renovated.']],['What does Joel offer to do?','Edit an image.',['Return to the property.','Hire another photographer.','Postpone an update.']],['When will the image most likely be used?','Friday.',['Tomorrow morning.','At 2:00 today.','During an evening event.']]]},
  {category:'公告 · 社區活動',passage:'GREENWAY VOLUNTEER DAY — Saturday, May 18\nHelp improve the walking trail beside Lake Monroe. Volunteers will plant trees, repaint signs, and collect litter. Check-in begins at 8:30 a.m. at the north picnic shelter. Gloves and tools will be provided. Please wear closed-toe shoes and bring a reusable water bottle. In case of severe weather, the event will be held on May 25.',questions:[['What is the purpose of the event?','To improve a public trail.',['To open a new restaurant.','To train park employees.','To sell gardening tools.']],['Where should volunteers report?','At the north picnic shelter.',['Beside the lake’s south entrance.','At a gardening store.','Inside a weather station.']],['What will be supplied?','Work tools.',['Shoes.','Water bottles.','Picnic meals.']],['What may cause the date to change?','Severe weather.',['A shortage of volunteers.','A closed parking lot.','A tree delivery.']]]},
  {category:'文章 · 公司成長',passage:'After starting as a weekend bakery stall six years ago, Golden Field Foods has opened its tenth retail location. Founder Priya Shah credits the company’s growth to seasonal ingredients and partnerships with nearby farms. The newest shop, located inside Central Station, is the first to offer mobile ordering. Shah says the feature will be introduced at three other busy locations later this year.',questions:[['What is the article mainly about?','The expansion of a food business.',['A farm ownership change.','A railway construction project.','A mobile phone manufacturer.']],['How did the business begin?','As a weekend stall.',['As a farm partnership.','Inside Central Station.','With ten retail locations.']],['What is special about the newest shop?','It offers mobile ordering.',['It is located on a farm.','It sells only seasonal drinks.','It opens only on weekends.']],['What will happen later this year?','More shops will add a feature.',['The founder will leave the company.','Central Station will close.','Three farms will open bakeries.']]]},
  {category:'行程表 · 培訓活動',passage:'CUSTOMER EXPERIENCE SUMMIT — July 9\n9:00 Opening remarks — Hall A\n9:30 Designing helpful chatbots — Hall A\n10:45 Break\n11:00 Handling difficult calls — Room 3\n12:15 Lunch — Garden Terrace\n1:30 Measuring customer satisfaction — Hall B\n3:00 Small-group coaching — Rooms 2–5\nNote: Participants in small-group coaching must select a room at the registration desk before lunch.',questions:[['What is scheduled first?','Opening remarks.',['A chatbot session.','Small-group coaching.','Lunch.']],['Where will the difficult-calls session take place?','Room 3.',['Hall A.','Hall B.','Garden Terrace.']],['What begins at 1:30?','A session on customer satisfaction.',['Lunch.','Registration.','A coaching session.']],['What must some participants do before lunch?','Select a room.',['Attend opening remarks.','Measure customer satisfaction.','Call the registration desk.']]]},
  {category:'雙篇閱讀 · 活動與郵件',passage:'DOCUMENT 1 — Harbor Technology Expo\nSeptember 21–22, Eastport Convention Center. Exhibitor setup: September 20, 2:00–7:00 p.m. Booth packages include one table, two chairs, and wireless Internet. Extra electrical service must be ordered by September 5.\n\nDOCUMENT 2 — From: Nia Brooks\nTo: Expo Team\nOur booth materials will arrive at the convention center on September 20 at 3:30. I ordered an additional power connection yesterday. Sam and I will handle setup; please send us the final product list by September 18.',questions:[['When may exhibitors begin setting up?','September 20 at 2:00 p.m.',['September 5 at 3:30 p.m.','September 18 at 7:00 p.m.','September 21 at 2:00 p.m.']],['What is included in a booth package?','Wireless Internet.',['Extra electrical service.','Product samples.','Shipping service.']],['What did Nia order?','An additional power connection.',['Two more chairs.','A larger booth.','A product list.']],['Who will set up the booth with Nia?','Sam.',['An electrical contractor.','The convention center manager.','A shipping driver.']]]},
  {category:'雙篇閱讀 · 交通與通知',passage:'DOCUMENT 1 — Route 8 Weekend Notice\nBecause of road resurfacing, Route 8 buses will not stop at Market Square on August 3–4. Passengers should use the temporary stop on King Street, approximately two blocks east. Normal service resumes Monday.\n\nDOCUMENT 2 — Message from Arden Hotel\nGuests arriving this weekend should be aware that the Market Square bus stop is closed. From the temporary King Street stop, walk west for two blocks and turn left at the pharmacy. The hotel entrance is beside the bookstore.',questions:[['Why is the Market Square stop closed?','A road is being resurfaced.',['A hotel is being renovated.','A pharmacy is moving.','Buses are being inspected.']],['Where is the temporary stop?','On King Street.',['Beside the bookstore.','At the hotel entrance.','West of the pharmacy.']],['When will normal service resume?','Monday.',['August 3.','Saturday evening.','After the hotel opens.']],['What landmark is next to the hotel entrance?','A bookstore.',['A pharmacy.','A bus station.','A market.']]]}
]

const part7 = readingPassages.flatMap((item, passageIndex) => item.questions.map((question, questionIndex) => buildQuestion({
  id:`gen-p7-${String(passageIndex * 4 + questionIndex + 1).padStart(3,'0')}`,
  part:'Part 7', category:item.category, difficulty:passageIndex > 5 || questionIndex > 1 ? '進階' : '中階', group:`Reading ${passageIndex + 1}`,
  passage:item.passage, prompt:question[0], explanation:`文中可定位或推論出的答案是：${question[1]}`, tags:['reading comprehension', passageIndex > 5 ? 'multiple passages' : 'single passage']
}, question[1], question[2], passageIndex + questionIndex)))

export const generatedQuestionBank = [...part1, ...part2, ...part3, ...part4, ...part5, ...part6, ...part7]

export const youtubeCompanionQuestionIds = [
  ...part2.slice(0, 12),
  ...part3.slice(0, 9),
  ...part4.slice(0, 9)
].map(question => question.id)
